### ISSUE TITLE
Can not find mapper in PKOnlyObject

### ISSUE THREAD

**Issue by fantom0005** [Relrin/aiorest-ws#80]
Hello, dear friend.
I have such an error in function _get_object_pk in SQLAlchemyMixin: 

```bash
Traceback (most recent call last):
  File "/usr/local/Cellar/python3/3.6.1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/asyncio/coroutines.py", line 210, in coro
    res = func(*args, **kw)
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/request.py", line 63, in onMessage
    response = self.factory.router.process_request(request)
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/routers.py", line 131, in process_request
    response.content = handler.dispatch(request, *args, **kwargs)
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/views.py", line 77, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/antonsvecov/Projects/betronic-white-label/admin/src/utils/decorators.py", line 21, in wrapper
    return handler(request, *args, **kwargs)
  File "/Users/antonsvecov/Projects/betronic-white-label/admin/src/utils/abstract_view.py", line 30, in get
    session, **kwargs)
  File "/Users/antonsvecov/Projects/betronic-white-label/admin/src/utils/abstract_view.py", line 20, in _get_model_all
    return self.serializer(items, many=True).data
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/serializers.py", line 635, in data
    ret = super(ListSerializer, self).data
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/serializers.py", line 154, in data
    self._data = self.to_representation(self.instance)
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/serializers.py", line 585, in to_representation
    return [self.child.to_representation(item) for item in data]
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/serializers.py", line 585, in <listcomp>
    return [self.child.to_representation(item) for item in data]
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/serializers.py", line 392, in to_representation
    ret[field.field_name] = field.to_representation(attribute)
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/sqlalchemy/relations.py", line 96, in to_representation
    object_pk = self._get_object_pk(value)
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/sqlalchemy/mixins.py", line 54, in _get_object_pk
    data = {str(field): getattr(obj, field) for field in pk_fields}
  File "/Users/antonsvecov/envs/wl/lib/python3.6/site-packages/aiorest_ws/db/orm/sqlalchemy/mixins.py", line 54, in <dictcomp>
    data = {str(field): getattr(obj, field) for field in pk_fields}
```

My code serializer:
```python
...

class EmailAuthSerializer(serializers.ModelSerializer):
    user = serializers.PrimaryKeyRelatedField(
        queryset=Query(UserModel), many=False, required=False,
    )

    class Meta:
        model = EmailAuthModel
        fields = ('email', 'user')
```
My models first model: 

```python
...

class EmailAuthModel(BaseModel):
    __tablename__ = "email_auth"

    SALT = "asdas"

    email = Column(String(256), primary_key=True)
    password_hash = Column(String(128))
    user_id = Column(ForeignKey("user.id"), nullable=True)
    user = relationship(
        "UserModel", back_populates="email_auth", foreign_keys=[user_id])

    verification_key = Column(String(64))
    verification_expiry = Column(DateTime)
```

My second model: 

```python
...

class UserModel(BaseModel):
    __tablename__ = "user"

    ORGANIZATION_ID = -1
    PAYMENTS_ID = -2
    WITHDRAWAL_ID = -3
    TICKET_USER_ID = -4
    BILL_ACCEPTOR_ID = -6

    ROLES = {'USER': '0', 'CASHIER': '1', 'ADMIN': '2', 'OWNER': '3'}

    id = Column(Integer, autoincrement=True, primary_key=True)
    first_name = Column(String(60))
    middle_name = Column(String)
    last_name = Column(String(60))
    nickname = Column(String(60), unique=True)
    role = Column(
        String(1), default=ROLES['USER'], server_default=ROLES['USER'])
    first_visit = Column(DateTime, default=datetime.utcnow)
    last_visit = Column(DateTime)
    city = Column(String)
    email_auth = relationship(
        EmailAuthModel, uselist=False, back_populates="user")

```

Please, fix this bug

**Comment by fantom0005** [comment]
BugFix:
```python 
    def _get_object_pk(self, obj):
        try:
            mapper = obj.__mapper__
        except:
            mapper = obj.pk.__mapper__
            obj = obj.pk
        model = mapper.class_
        pk_fields = model_pk(model)
        data = {str(field): getattr(obj, field) for field in pk_fields}
        return data if len(pk_fields) > 1 else data[pk_fields[0]]
```
But, I thought that you can immediately serialize the model's dependence on the fields, so it would be convenient to not make many requests

**Comment by Relrin** [comment]
Hi, fantom0005!

Thanks for opening an issue here.
I guess, this error occurred because you have specified a relation between the User and EmailAuth models, where email_auth relation in User model has the ```uselist=False``` named parameter. In terms of SQLAlchemy it means, that we will set an object for relation (as an attribute of model instance) instead of appending it to a list. Therefore, it leads to errors in runtime, because serializers trying to get primary keys for nested objects object (in our case it is email's PK) and [put it into PKOnlyObject instance](https://github.com/Relrin/aiorest-ws/blob/master/aiorest_ws/db/orm/sqlalchemy/relations.py#L60-L62). After that in ```to_representation``` method a server propagates an error, because we expect to get an instance of model here.

**Comment by Relrin** [comment]
Fix was done in [pull request](https://github.com/Relrin/aiorest-ws/pull/81)
